[jenkins-master]
10.0.0.244
[jenkins-master:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/opt/ttn-key01.pem
[jenkins-slave]
10.0.25.60
[jenkins-slave:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/opt/ttn-key01.pem
